import { useEffect, useState } from 'react';
import { Boxes, Edit3, Plus, Search, Trash2, TriangleAlert } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { adminApi } from '../../services/api';
const money = (value = 0) => `₹${Number(value).toLocaleString('en-IN')}`;
export default function AdminProducts() {
  const [params] = useSearchParams(); const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); Promise.all([adminApi.products({ search, category, stock: params.get('stock'), limit: 100 }), adminApi.categories()]).then(([p, c]) => { setProducts(p.data); setCategories(c.data); }).catch(() => toast.error('Unable to load products')).finally(() => setLoading(false)); };
  useEffect(load, [category, params]);
  const remove = async (product) => { if (!window.confirm(`Delete ${product.name}? This cannot be undone.`)) return; try { await adminApi.deleteProduct(product._id); toast.success('Product deleted'); load(); } catch (e) { toast.error(e.response?.data?.message || 'Delete failed'); } };
  return <div className="admin-page"><div className="admin-page-title"><div><p>Catalogue control</p><h1>Products</h1></div><Link className="admin-primary" to="/admin/products/new"><Plus/>Add product</Link></div><section className="admin-panel"><div className="admin-filters"><label><Search/><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder="Search products"/></label><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All categories</option>{categories.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><button onClick={load}>Search</button></div>
    {loading ? <div className="admin-table-loading">Loading products…</div> : products.length ? <div className="admin-table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Original</th><th>Selling</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product._id}><td><div className="admin-product-cell"><img src={product.image || '/assets/hero-fireworks.png'} alt=""/><div><strong>{product.name}</strong><small>{product.sku || product.sourceNumber}</small></div></div></td><td>{product.category?.name}</td><td>{money(product.originalPrice)}</td><td><strong>{money(product.price)}</strong></td><td>{product.stockQuantity < (product.lowStockThreshold || 10) && product.stockQuantity > 0 ? <span className="low-stock"><TriangleAlert/> {product.stockQuantity}</span> : product.stockQuantity}</td><td><span className={`status ${product.isActive ? 'status-active' : 'status-cancelled'}`}>{product.isActive ? product.status : 'disabled'}</span></td><td><div className="admin-actions"><Link to={`/admin/products/${product._id}/edit`} aria-label="Edit"><Edit3/></Link><button onClick={() => remove(product)} aria-label="Delete"><Trash2/></button></div></td></tr>)}</tbody></table></div> : <div className="admin-empty"><Boxes/><h2>No products found</h2></div>}</section></div>;
}
