import { useEffect, useState } from 'react';
import { Edit3, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { adminApi } from '../../services/api';
export default function AdminCategories() {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ name: '', description: '', displayOrder: 0, isActive: true }); const [editing, setEditing] = useState(null);
  const load = () => adminApi.categories().then((r) => setItems(r.data)).catch(() => toast.error('Unable to load categories')); useEffect(load, []);
  const save = async (event) => { event.preventDefault(); try { editing ? await adminApi.updateCategory(editing, form) : await adminApi.createCategory(form); toast.success(editing ? 'Category updated' : 'Category added'); setEditing(null); setForm({ name: '', description: '', displayOrder: 0, isActive: true }); load(); } catch (e) { toast.error(e.response?.data?.message || 'Unable to save category'); } };
  const edit = (item) => { setEditing(item._id); setForm({ name: item.name, description: item.description || '', displayOrder: item.displayOrder || 0, isActive: item.isActive !== false }); };
  const remove = async (item) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await adminApi.deleteCategory(item._id); toast.success('Category deleted'); load(); } catch (e) { toast.error(e.response?.data?.message || 'Delete failed'); } };
  return <div className="admin-page"><div className="admin-page-title"><div><p>Catalogue structure</p><h1>Categories</h1></div></div><div className="admin-split"><form className="admin-panel admin-category-form" onSubmit={save}><h2>{editing ? 'Edit category' : 'Add category'}</h2><label>Name *<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label>Description<textarea rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label><label>Display order<input type="number" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })}/></label><label className="admin-check"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })}/>Active category</label><button className="admin-primary"><Plus/>{editing ? 'Update' : 'Add'} category</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm({ name: '', description: '', displayOrder: 0, isActive: true }); }}>Cancel</button>}</form><section className="admin-panel"><div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Category</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td>{item.displayOrder}</td><td><strong>{item.name}</strong><small className="admin-block">{item.description}</small></td><td><span className={`status ${item.isActive !== false ? 'status-active' : 'status-cancelled'}`}>{item.isActive !== false ? 'Active' : 'Disabled'}</span></td><td><div className="admin-actions"><button onClick={() => edit(item)}><Edit3/></button><button onClick={() => remove(item)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section></div></div>;
}
